### ISSUE TITLE
can't sign in with google and facebook account

### ISSUE THREAD

**Issue by DianaDai-meh** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#14]
<img width="641" alt="Screen Shot 2020-12-14 at 4 22 55 PM" src="https://user-images.githubusercontent.com/75862075/102137313-a43ce400-3e28-11eb-8288-7ba9104bb8bd.png">

**Comment by JalenYes** [comment]
@kaichunwu  Can you help take care of OAuth quickly? I tried a couple of times. There might be something wrong beyond configuration. I added kwu@youplanets.com to Google OAuth and Facebook OAuth console. Thank you! pls let me know if you have any questions.

**Comment by JalenYes** [comment]
https://beta.youplanets.com/api/planets/topplanet and https://youplanets-server.herokuapp.com/api/planets/topplanet all can reach the endpoint. you might consider put https://beta.youplanets.com/api/auth/facebook/callback as callback instead of youplanets-server.herokuapp.com.

**Comment by kaichunwu** [comment]
Don't have permission to the google OAuth
<img width="820" alt="Screen Shot 2020-12-15 at 15 02 17" src="https://user-images.githubusercontent.com/44331917/102283081-89c94000-3ee6-11eb-85d2-94b0bd366c1b.png">

**Comment by JalenYes** [comment]
Thank you for letting me know! Access regranted to kwu@youplanets.com again.

**Comment by JalenYes** [comment]
For some reason, it still doesn't work on the production. let me know if you need any help from me.

**Comment by JalenYes** [comment]
No worries. I think we might need a new branch for dev production. It could make dev testing easier a lot.

**Comment by JalenYes** [comment]
It works. However, the first page after signed in with Google and Facebook OAuth is this:  
<img width="1548" alt="image" src="https://user-images.githubusercontent.com/40333215/102290196-7e8a0a80-3f0e-11eb-826e-beb04127b70d.png">

Can we redirect users to https://beta.youplanets.com/myspace/following after OAuth? It would make more sense.

**Comment by JalenYes** [comment]
Looks awesome now! Thank you so much!

**Comment by Seraph-YCZhang** [comment]
Sorry to reopen this. But Facebook OAuth is still not working.

**Comment by Seraph-YCZhang** [comment]
![image](https://user-images.githubusercontent.com/20440998/102420306-db012e80-3fcf-11eb-97e4-17d76b7bfc27.png)

loading for a while

![image](https://user-images.githubusercontent.com/20440998/102420331-e9e7e100-3fcf-11eb-9dc3-17ddb9547f95.png)

and this URL https://beta.youplanets.com/api/auth/facebook/callback?code=AQDbrs3yYJtEmrJ2g1Tv0GeXFHwsUIIqFm46tn3RSZg2OEy8v1bF1ohKXB4L8iIfP5LALPHURZGiR2AspKfNu80UrEanXxXtuoOSUAjHR63IsdUgQL_6lv-l6KTMc8kIOK0B-XA(delete part of code )C93usnLY3vcPA-xJ-w76tvkfz9I5U5fahCr7UomlPe6q7GfbXBKNeizRneylULZxleJLWaxOfj5T5FVP0bV9Ax_dS6oXmw7wm3oCOFKmoRAjwQ5CmI2c#_=_

**Comment by Seraph-YCZhang** [comment]
2020-12-17T00:03:06.571454+00:00 heroku[router]: at=info method=GET path="/api/auth/facebook/callback?code=AQBjhpT6P(........)qr7oO0SR9lVhPh9SN1W0DxFMJ7lAFh0IDyIKgO-MODzKQ553UkExKvHpbtzuWl349BkZVgOQE-2Vg3AcvGZlKEcZYRFmHzNg1svwqkSQo8hX-uglxdpWzWRBn_IKV7pRkNnGtqWH1pQYlZZsm8hCgGf1IG0m4owmZfv9n0Ar_ihAtuz0efp_47f8M16gFMQxT1oPXZ6LQwbBAQAD3YMPeHpepktgptb3n" host=youplanets-server.herokuapp.com request_id=c9877df1-803b-4453-bd13-34473d6b6236 fwd="67.170.60.159,3.93.64.125" dyno=web.1 connect=0ms service=303ms status=500 bytes=458 protocol=https
2020-12-17T00:03:06.568774+00:00 app[web.1]: error: value too long for type character varying(255)

**Comment by Seraph-YCZhang** [comment]
@kaichunwu

**Comment by kaichunwu** [comment]
got it. Fixed. Because of users table has 255 length limit for photo

**Comment by JalenYes** [comment]
> got it. Fixed. Because of users table has 255 length limit for photo

That's wonderful!  whenever you push

**Comment by Seraph-YCZhang** [comment]
Still not working for me...
I guess the reason is I got rejected last time, and there was something weird happened

You can check the log

here is part of it
```
2020-12-17T03:22:25.433370+00:00 app[web.1]: (node:36) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
2020-12-17T03:22:25.433379+00:00 app[web.1]:     at Strategy.passportController.FacebookStrategyCallback [as _verify] (/app/src/controllers/passportController.js:110:21)
2020-12-17T03:22:25.433383+00:00 app[web.1]:     at /app/node_modules/passport-oauth2/lib/strategy.js:202:24
2020-12-17T03:22:25.433384+00:00 app[web.1]:     at /app/node_modules/passport-facebook/lib/strategy.js:183:5
2020-12-17T03:22:25.433384+00:00 app[web.1]:     at passBackControl (/app/node_modules/oauth/lib/oauth2.js:134:9)
2020-12-17T03:22:25.433385+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:157:7)
2020-12-17T03:22:25.433386+00:00 app[web.1]:     at IncomingMessage.emit (events.js:326:22)
2020-12-17T03:22:25.433386+00:00 app[web.1]:     at IncomingMessage.EventEmitter.emit (domain.js:483:12)
2020-12-17T03:22:25.433386+00:00 app[web.1]:     at endReadableNT (_stream_readable.js:1241:12)
2020-12-17T03:22:25.433387+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-12-17T03:22:25.433394+00:00 app[web.1]: (node:36) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
2020-12-17T03:22:55.193279+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/api/auth/facebook/callback?code=AQCFF3CC4SpAqu7k92FIoRAni-1UcCNdxnT-zTM1al2heRVz8DXTVVRo7Sg_Dx80Y2xYjrH3lm69KhzQ2e9kbKaUq9chb70cmsAFLhrbskB_XTaXcKPMjbI1fbqCGELdxD5zfWGO1xtDGrIrO1MGsqix-x408IpMijsXGxQUpDqcacz2jMpUrNncLzMUHT4bSoKaJNQOtK0fZZHAu0jvdfVc8EiQyWM6utRUk1EkJnh096_kk3YXJYVBTpMULp3GSVAnbVJV6jYPVRDyFM2Z3Wdoo-Wxq-QgLec" host=youplanets-server.herokuapp.com request_id=45bb40ba-2b29-4d38-a0fd-750818b8d0fa fwd="68.133.23.98,18.215.183.158" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=https
2020-12-17T03:22:55.319955+00:00 app[web.1]: FacebookTokenError: This authorization code has been used.
2020-12-17T03:22:55.319963+00:00 app[web.1]:     at Strategy.parseErrorResponse (/app/node_modules/passport-facebook/lib/strategy.js:198:12)
2020-12-17T03:22:55.319964+00:00 app[web.1]:     at Strategy.OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:405:16)
2020-12-17T03:22:55.319965+00:00 app[web.1]:     at /app/node_modules/passport-oauth2/lib/strategy.js:175:45
2020-12-17T03:22:55.319965+00:00 app[web.1]:     at /app/node_modules/oauth/lib/oauth2.js:191:18
2020-12-17T03:22:55.319966+00:00 app[web.1]:     at passBackControl (/app/node_modules/oauth/lib/oauth2.js:132:9)
2020-12-17T03:22:55.319966+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:157:7)
2020-12-17T03:22:55.319967+00:00 app[web.1]:     at IncomingMessage.emit (events.js:326:22)
2020-12-17T03:22:55.319968+00:00 app[web.1]:     at IncomingMessage.EventEmitter.emit (domain.js:483:12)
2020-12-17T03:22:55.319968+00:00 app[web.1]:     at endReadableNT (_stream_readable.js:1241:12)

```

**Comment by kaichunwu** [comment]
Do you have any email linked to your facebook account?

**Comment by Seraph-YCZhang** [comment]
> Do you have any email linked to your facebook account?

Probably not. I cannot find my email in my FB.

**Comment by kaichunwu** [comment]
I think this is the question. Actually our app is email based app. This should be one possible issue for our whole app.

**Comment by JalenYes** [comment]
What do you mean by the email-based app? we designed to put email as the unique identifier for a user

**Comment by kaichunwu** [comment]
I mean one account/user must have one unique email address linked to it. Otherwise, lots of issues will happen.

**Comment by JalenYes** [comment]
> I mean one account/user must have one unique email address linked to it. Otherwise, lots of issues will happen.

yes, that's how we set up it initially. but how does it do with OAuth?

**Comment by kaichunwu** [comment]
This line is wrong.
`let email = emails[0].value;`
we can quickly fix that. But eventually we need the email, for lots of cases.

**Comment by JalenYes** [comment]
@kaichunwu  Any updates?

**Comment by JalenYes** [comment]
@Seraph-YCZhang  Can you login with your Facebook account again? What's the error message?

**Comment by JalenYes** [comment]
This issue has not been fixed. But this is really tricky. So I will close this issue for now. But keep the record for sure.
